# This is a basic workflow to help you get started with Actions

name: GCP

# Controls when the workflow will run
on:
  push:
    branches: [ menulis ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: "sudo su && cd /var/www/soon && git pull origin menulis"
